version: '3'

services:
  app:
    image: nginx:latest
    ports:
      - 38907:80
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - php
  php:
    image: php:8-apache
    volumes:
      - ./src:/var/www/html:ro
    networks:
      - internal
  bot:
    build: bot
    environment:
      APPNAME: Admin
      APPURL: http://app/
      APPURLREGEX: ^.*$
      APPFLAG: TCF2023{252d8e3b-0367-4005-a4b7-ea40c410d566}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

networks:
  internal:
