version: '3'

services:
  app:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
  bot:
    build: bot
    environment:
      APPNAME: Dimas
      APPURL: http://app/
      APPURLREGEX: http://app/.*
      APPFLAG: INTECHFEST{some_assembly_will_make_your_day_better_4ba32eeceee4bc897d3f3d1bf8a005cf}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

networks:
  internal:
