version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 53622:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - app
  app:
    build: .
    networks:
      - internal
  bot:
    build: bot
    environment:
      APPNAME: Admin
      APPURL: http://app:8080/
      APPURLREGEX: ^http://app:8080/.*$
      APPFLAG: STS23{xss_in_url_path!you_must_be_kidding_right?}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

networks:
  internal:
