version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 39046:80
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - app
  app:
    build: .
    networks:
      - internal
  bot:
    build: bot
    environment:
      APPNAME: Admin
      APPURL: http://app:3000/
      APPURLREGEX: ^http://app:3000/.*$
      APPFLAG: TCF2024{xss_on_the_path_is_really_out_of_this_world!}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

networks:
  internal:
