version: '3'

services:
  app:
    build: ./src
    restart: always
    ports:
      - "7716:8080"
    networks:
      internal:
  db:
    image: mongo:latest
    restart: always
    environment:
      FLAG: INTECHFEST{FTPPasvRedirect}
    volumes:
      - "./db/:/docker-entrypoint-initdb.d/:ro"
    networks:
      internal:
networks:
  internal:
